version: '3.1'
services:
  app:
    container_name: hookcmd
    build: .
    working_dir: /app
    env_file: .env
    volumes:
     - "./data:/app/data"
     - "./.env:/app/.env"
     - "/root/.npm/_cacache:/root/.npm/_cache"
    entrypoint:
      - sh 
      - ./docker-entry.sh
    networks:
          - mba_default

networks:
  mba_default:
    external:
      name: mba_default